In [1]:
import fsps
import numpy as np



In [2]:
SFH_age = np.linspace(0.0, 100.0, num=1001)  # in Myr
SFH_sfr = np.ones(len(SFH_age))
print SFH_age

[   0.     0.1    0.2 ...,   99.8   99.9  100. ]


In [6]:
sp = fsps.StellarPopulation(compute_vega_mags=False, zcontinuous=1, imf_type=0, add_neb_emission=True,
                                      sfh=3, logzsol=0.0, dust_type=2, dust2=0.0)

sp.set_tabular_sfh(10**-3*SFH_age, SFH_sfr, Z=None)  # age in Gyr

print sp.get_mags(tage=10**-3*100.0, bands=['i1500', 'i2300', 'i2800'])


[-17.97213386 -17.85832523 -17.77317424]


In [7]:
sp = fsps.StellarPopulation(compute_vega_mags=False, zcontinuous=1, imf_type=0, add_neb_emission=True,
                                      sfh=3, logzsol=0.0, dust_type=2, dust2=0.0)

sp.set_tabular_sfh(10**-3*SFH_age[::2], SFH_sfr[::2], Z=None)  # age in Gyr

print sp.get_mags(tage=10**-3*100.0, bands=['i1500', 'i2300', 'i2800'])


[-17.97213386 -17.85832523 -17.77317424]


In [8]:
sp = fsps.StellarPopulation(compute_vega_mags=False, zcontinuous=1, imf_type=0, add_neb_emission=True,
                                      sfh=3, logzsol=0.0, dust_type=2, dust2=0.0)

sp.set_tabular_sfh(10**-3*SFH_age[::2], SFH_sfr[::2], Z=None)  # age in Gyr

print sp.get_mags(tage=10**-3*99.9, bands=['i1500', 'i2300', 'i2800'])


[-17.97201811 -17.85817788 -17.77299149]
